# Generated by Django 5.0.2 on 2024-04-02 21:20

import django.db.models.deletion
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline_code', models.CharField(help_text='Код для авіакомпанії', max_length=6)),
                ('name', models.CharField(help_text='Повна назва авіакомпанії', max_length=100)),
                ('website', models.URLField(help_text='Посилання на домашній сайт')),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airport_code', models.CharField(help_text='Код аеропорту', max_length=50)),
                ('airport_name', models.CharField(help_text='Повна назва аеропорту', max_length=100)),
                ('city', models.CharField(help_text='Місто знаходження аеропорту', max_length=50)),
                ('country', django_countries.fields.CountryField(help_text='Країна якій належить даний аеропорт', max_length=2)),
            ],
            options={
                'ordering': ['-airport_name'],
            },
        ),
        migrations.CreateModel(
            name='Airplane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Назва літака', max_length=100)),
                ('model', models.CharField(help_text='Модель літака', max_length=100)),
                ('tail_number', models.CharField(help_text='Реєстраційний номер літака', max_length=24, unique=True)),
                ('num_seats', models.IntegerField(help_text='Кількість місць в літаку')),
                ('airline', models.ForeignKey(help_text='Якій авіакомпанії компанії належить', on_delete=django.db.models.deletion.CASCADE, to='ticket_store.airline')),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_code', models.CharField(help_text='Код рейсу', max_length=8)),
                ('departure_date', models.DateTimeField(help_text='Дата та час відправлення')),
                ('arrival_date', models.DateTimeField(help_text='Дата та час прибуття')),
                ('ticket_price', models.DecimalField(decimal_places=2, help_text='Вартість квитка для цього рейсу', max_digits=6)),
                ('airplane', models.ForeignKey(help_text='Який літак буде здійснювати рейс', on_delete=django.db.models.deletion.CASCADE, to='ticket_store.airplane')),
                ('arrival_airport', models.ForeignKey(help_text='Аеропорт, в який прибувають', on_delete=django.db.models.deletion.CASCADE, related_name='arrival_airport', to='ticket_store.airport')),
                ('departure_airport', models.ForeignKey(help_text='Аеропорт, з якого відправляються', on_delete=django.db.models.deletion.CASCADE, related_name='departure_airport', to='ticket_store.airport')),
            ],
            options={
                'ordering': ['-departure_date'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PEND', 'pending'), ('CONF', 'confirmed'), ('CANC', 'canceled')], default='PEND', help_text='Статус оплати бронювання', max_length=4)),
                ('user', models.ForeignKey(blank=True, default=None, help_text='Хто купив даний квиток', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('flight', models.ForeignKey(help_text='На який рейс бронювання квитку', on_delete=django.db.models.deletion.CASCADE, to='ticket_store.flight')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(help_text='Дата та час транзакції')),
                ('ammount_paid', models.DecimalField(decimal_places=2, help_text='Вартість квитка для цього рейсу', max_digits=14)),
                ('booking', models.ForeignKey(help_text="З яким бронюванням пов'язано", null=True, on_delete=django.db.models.deletion.SET_NULL, to='ticket_store.booking')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_num', models.IntegerField(help_text='Місце в літаку')),
                ('bought', models.BooleanField(default=False, help_text='Чи був квиток вже куплений')),
                ('flight', models.ForeignKey(help_text='Рейс, на якому можна використати даний квиток', on_delete=django.db.models.deletion.CASCADE, to='ticket_store.flight')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='ticket',
            field=models.OneToOneField(help_text='Який саме квиток', on_delete=django.db.models.deletion.CASCADE, to='ticket_store.ticket'),
        ),
    ]
