# Generated by Django 5.0.2 on 2024-04-03 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='ammount_paid',
            field=models.DecimalField(decimal_places=2, help_text='Сплачена сума за бронювання', max_digits=6),
        ),
        migrations.AlterField(
            model_name='payment',
            name='booking',
            field=models.OneToOneField(help_text="З яким бронюванням пов'язано", null=True, on_delete=django.db.models.deletion.SET_NULL, to='ticket_store.booking'),
        ),
    ]
