# Generated by Django 5.0.2 on 2024-04-03 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_store', '0002_alter_payment_ammount_paid_alter_payment_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateTimeField(help_text='Дата та час транзакції'),
        ),
    ]
